name: Webinizer-webclient CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "security.md"
      - "SUPPORT.md"
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "security.md"
      - "SUPPORT.md"
  # allow to be triggered manually
  workflow_dispatch:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1

      - name: Install tool dependencies
        run: npm install

      - name: Linting Check
        run: npm run lint
